AWSTemplateFormatVersion: '2010-09-09'
Description: 'Personalize HOL CloudFormation Template - IAM roles and SageMaker Notebook (Recommended Stack Name: Personalize-HOL)'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups: []
  RecommendedStackName: 'Personalize-HOL'

Resources:
  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: "ml.t3.xlarge"
      DirectInternetAccess: "Enabled"
      NotebookInstanceName: "Personalize-Notebook"
      RoleArn: !GetAtt SageMakerRole.Arn
      VolumeSizeInGB: 100
  SageMakerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: My-SageMakerRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/IAMFullAccess"
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/service-role/AmazonPersonalizeFullAccess"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - sagemaker.amazonaws.com
          Action:
            - sts:AssumeRole